// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBA.Models;

namespace NBA.Migrations
{
    [DbContext(typeof(NBAContext))]
    [Migration("20210331223248_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NBA.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AllStars")
                        .HasColumnType("int");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<int>("NbaPlayersChampionships")
                        .HasColumnType("int");

                    b.Property<int>("PlayOffs")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Team")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBA.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("NbaTeamsChampionships")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Location = "Atlanta",
                            NbaTeamsChampionships = 7,
                            TeamName = "Hawks"
                        },
                        new
                        {
                            TeamId = 2,
                            Location = "Boston",
                            NbaTeamsChampionships = 7,
                            TeamName = "Celtics"
                        },
                        new
                        {
                            TeamId = 3,
                            Location = "Brooklyn",
                            NbaTeamsChampionships = 7,
                            TeamName = "Nets"
                        },
                        new
                        {
                            TeamId = 4,
                            Location = "Hornets",
                            NbaTeamsChampionships = 7,
                            TeamName = "Hornets"
                        },
                        new
                        {
                            TeamId = 5,
                            Location = "Chicago",
                            NbaTeamsChampionships = 7,
                            TeamName = "Bulls"
                        },
                        new
                        {
                            TeamId = 6,
                            Location = "Cleveland",
                            NbaTeamsChampionships = 7,
                            TeamName = "Cavaliers"
                        },
                        new
                        {
                            TeamId = 7,
                            Location = "Dallas",
                            NbaTeamsChampionships = 7,
                            TeamName = "Mavericks"
                        },
                        new
                        {
                            TeamId = 8,
                            Location = "Denver",
                            NbaTeamsChampionships = 7,
                            TeamName = "Nuggets"
                        },
                        new
                        {
                            TeamId = 9,
                            Location = "Detroit",
                            NbaTeamsChampionships = 7,
                            TeamName = "Pistons"
                        },
                        new
                        {
                            TeamId = 10,
                            Location = "Golden State",
                            NbaTeamsChampionships = 7,
                            TeamName = "Warriors"
                        },
                        new
                        {
                            TeamId = 11,
                            Location = "Houston",
                            NbaTeamsChampionships = 7,
                            TeamName = "Rockets"
                        },
                        new
                        {
                            TeamId = 12,
                            Location = "Indiana",
                            NbaTeamsChampionships = 7,
                            TeamName = "Pacers"
                        },
                        new
                        {
                            TeamId = 13,
                            Location = "Los Angeles",
                            NbaTeamsChampionships = 7,
                            TeamName = "Clippers"
                        },
                        new
                        {
                            TeamId = 14,
                            Location = "Los Angeles",
                            NbaTeamsChampionships = 7,
                            TeamName = "Lakers"
                        },
                        new
                        {
                            TeamId = 15,
                            Location = "Memphis",
                            NbaTeamsChampionships = 7,
                            TeamName = "Grizzlies"
                        },
                        new
                        {
                            TeamId = 16,
                            Location = "Miami",
                            NbaTeamsChampionships = 7,
                            TeamName = "Heat"
                        },
                        new
                        {
                            TeamId = 17,
                            Location = "Milwaukee",
                            NbaTeamsChampionships = 7,
                            TeamName = "Bucks"
                        },
                        new
                        {
                            TeamId = 18,
                            Location = "Minnesota",
                            NbaTeamsChampionships = 7,
                            TeamName = "Timberwolves"
                        },
                        new
                        {
                            TeamId = 19,
                            Location = "Charlotte",
                            NbaTeamsChampionships = 7,
                            TeamName = "Hornets"
                        },
                        new
                        {
                            TeamId = 20,
                            Location = "New York",
                            NbaTeamsChampionships = 7,
                            TeamName = "Knicks"
                        },
                        new
                        {
                            TeamId = 21,
                            Location = "Oklakhoma",
                            NbaTeamsChampionships = 7,
                            TeamName = "Thunder"
                        },
                        new
                        {
                            TeamId = 22,
                            Location = "San Antonio",
                            NbaTeamsChampionships = 7,
                            TeamName = "Spurs"
                        },
                        new
                        {
                            TeamId = 23,
                            Location = "Orlando",
                            NbaTeamsChampionships = 7,
                            TeamName = "Magic"
                        },
                        new
                        {
                            TeamId = 24,
                            Location = "Philadelphia",
                            NbaTeamsChampionships = 7,
                            TeamName = "76ers"
                        },
                        new
                        {
                            TeamId = 25,
                            Location = "Phoenix",
                            NbaTeamsChampionships = 7,
                            TeamName = "Suns"
                        },
                        new
                        {
                            TeamId = 26,
                            Location = "Portland",
                            NbaTeamsChampionships = 7,
                            TeamName = "Trail Blazers"
                        },
                        new
                        {
                            TeamId = 27,
                            Location = "Sacramento",
                            NbaTeamsChampionships = 7,
                            TeamName = "Kings"
                        },
                        new
                        {
                            TeamId = 28,
                            Location = "Toronto",
                            NbaTeamsChampionships = 7,
                            TeamName = "Raptors"
                        },
                        new
                        {
                            TeamId = 29,
                            Location = "Utah",
                            NbaTeamsChampionships = 7,
                            TeamName = "Jazz"
                        },
                        new
                        {
                            TeamId = 30,
                            Location = "Washington",
                            NbaTeamsChampionships = 7,
                            TeamName = "Wizards"
                        },
                        new
                        {
                            TeamId = 31,
                            Location = "NBA",
                            NbaTeamsChampionships = 7,
                            TeamName = "Free Agents"
                        });
                });

            modelBuilder.Entity("NBA.Models.Player", b =>
                {
                    b.HasOne("NBA.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NBA.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
